repos:
- repo: https://github.com/astral-sh/uv-pre-commit
  # uv version.
  rev: 0.6.6
  hooks:
    # Update the uv lockfile
    - id: uv-lock
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.11.0
  hooks:
    # Run the linter.
    - id: ruff
      args: [ --fix ]
    # Run the formatter.
    - id: ruff-format
- repo: https://github.com/RobertCraigie/pyright-python
  rev: v1.1.396
  hooks:
    - id: pyright
- repo: local
  hooks:
    - id: pytest
      name: pytest
      entry: ./.venv/bin/pytest tests
      language: python
      pass_filenames: false
      always_run: true